## Билет 3
### Решение систем линейных алгебраических уравнений с трехдиагональной матрицей методом прогонки.

**Определение.** Система $Ax=f$ называется с *диагональным преобладанием*, если элементы матрицы $A$ удовлетворяют неравенствам
$$ \left| a_{ii} \right| > \sum_{\substack{j=1 \\ j \not = i}}^n{\left | a_{ij} \right|},\quad 1 \leq i \leq n. $$

**Теорема.** Система с диагональным преобладанием всегда разрешима единственным образом.

$\blacktriangle$ Рассмотрим однородную систему 
$$\sum\limits_{j=1}^n{a_{ij}x_j}=0,\quad 1 \leq i \leq n.$$
Пусть она имеет *нетривиальное решение* $\bar x$. Пусть наибольшая по модулю компонента решения соответсвует индексу $j=k$, т.е.
$$\left | \bar x_k \right| > 0, \quad \left | \bar x_k \right | \geq \left | \bar x_j \right |,\quad 1 \leq j \leq n.$$
Запишем $k$-ое уравнение системы в виде:
$$ a_{kk} \bar x_k = -\sum\limits_{\substack{j=1 \\ j \not = k}}^n{a_{kj} \bar x_j}.$$
Возьмем модуль от обеих частей равенства и получим:
$$ 
\left| a_{kk} \right| \left| \bar x_k \right| 
\leq 
\sum\limits_{\substack{j=1 \\ j \not = k}}^n{
    \left| a_{kj} \right| \left| \bar x_j \right|
}
\leq
\sum\limits_{\substack{j=1 \\ j \not = k}}^n{
    \left| a_{kj} \right| \left| \bar x_k \right|
}
$$
Сокращая неравенство на $\left| \bar x_k \right| \not = 0$, получим:
$$
\left| a_{kk} \right|
\leq
\sum\limits_{\substack{j=1 \\ j \not = k}}^n{
    \left| a_{kj} \right|
}
$$
Противоречие.

Таким образом
1. Однородная система с диагональным преобладанием имеет только тривиальное решение $\Rightarrow$
2. Определитель матрицы $A$ с диагональным преобладанием не равен нулю $\Rightarrow$
3. Неоднородная система с диагональным преобладанием всегда разрешима единственным образом.
$\blacksquare$

### Метод прогонки.

Рассмотрим СЛАУ вида
$$ A_ix_{i-1} + C_ix_i + B_ix_{i+1} = F_i,\quad i = 1,\ldots ,n $$
$$ x_0 = q_0, \; x_{n+1} = q_{n+1}. $$
(Последние два равенства задают *краевые условия*)

Запишем эту систему в виде:
$$
\begin{aligned}
    C_1x_1 + B_1x_2 &= F_1 - A_1q_0; \\
    A_2x_2 + C_2x_3 + B_2x_4 &= F_2; \\
    \cdots \\
    A_nx_{n-1} + C_nx_n &= F_n - A_nq_{n+1}.
\end{aligned}
$$

Матрица этой системы имеет трехдиагональную структуру:

$$
\begin{bmatrix}
    C_1 & B_1 & 0 & 0 & \ldots & 0 & 0 \\
    A_2 & C_2 & B_2 & 0 & \ldots & 0 & 0 \\
    0 & A_3 & C_3 & B_3 & \ldots & 0 & 0 \\
    \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots \\
    0 & 0 & 0 & 0 & \ldots & A_n & C_n
\end{bmatrix}
$$

**Метод прогонки** основан на предположении, что искомые неизвестные $x_i$ и $x_{i+1}$ связаны рекуррентным соотношением 
$$ x_i = \alpha_{i+1}x_{i+1} + \beta_{i+1},\quad 0 \leq i \leq n. $$
Величины $\alpha_i$ и $\beta_i$ называются *прогоночными коэффициентами*. По сути, задача нахождения корней свелась к нахождению прогоночных коэффициентов и последующих вычислений по ним корней.

**Как найти прогоночные коэффициенты?** Выразим $x_{i-1}$ через $x_{i+1}$:
$$ 
    x_{i-1} =
    \alpha_ix_i + \beta_i =
    \alpha_i\alpha_{i+1}x_{i+1} + \alpha_i\beta_{i+1} + \beta_i
$$
и подставим $x_{i-1}$ и $x_i$ в исходные уравнения:
$$
    (A_i\alpha_i\alpha_{i+1} + C_i\alpha_{i+1} + B_i)x_{i+1} +
    A_i\alpha_i\beta_{i+1} + A_i\beta_i + C_i\beta_{i+1} - F_i
    = 0,\quad i = 1,\ldots,n.
$$

Последнее будет выполнятся всегда (независимо от решения), если потребовать выполнения:
$$
\begin{aligned}
    & A_i\alpha_i\alpha_{i+1} + C_i\alpha_{i+1} + B_i = 0 \\
    & A_i\alpha_i\beta_{i+1} + A_i\beta_i + C_i\beta_{i+1} - F_i = 0 \\
    & i = 1,\ldots,n.
\end{aligned}
$$

Отсюда получаем:
$$
\begin{aligned}
    & \alpha_{i+1} = \frac{-B_i}{A_i\alpha_i + C_i}, \\
    & \beta_{i+1} = \frac{F_i - A_i\beta_i}{A_i\alpha_i + C_i}, \\
    & i = 1, \ldots, n.
\end{aligned}
$$

Левое граничное условие $x_0 = q_0$ и соотношение $x_0 = \alpha_1x_1 + \beta_1$ не противоречат, если положить
$$ \alpha_1 = 0,\quad \beta_1 = q_0. $$

Остальные значения коэффициентов прогонки $\alpha_2,\ldots,\alpha_{n+1}$ и $\beta_2,\ldots,\beta_{n+1}$ вычисляются по рекурентным формулам.

Согласно граничному условию,
$$ x_{n+1} = q_{n+1}. $$
Корни $x_n,\ldots,x_1$ вычисляются по рекурентной формуле.

#### Пример

In [1]:
#подключим библиотеку для работы с "матрицами"
import numpy as np

In [2]:
A = np.array(
        [[2, -1, 0, 0, 0],
         [-3, 8, -1, 0, 0],
         [0, -5 ,12, 2, 0],
         [0, 0, -6, 18, -4],
         [0, 0, 0, -5, 10]]
    )
f = np.array([-25, 72, -69, -156, 20])
f.shape = (f.shape[0], 1)
Af = np.hstack((A, f)) #A = [A|f]
print(Af)

[[   2   -1    0    0    0  -25]
 [  -3    8   -1    0    0   72]
 [   0   -5   12    2    0  -69]
 [   0    0   -6   18   -4 -156]
 [   0    0    0   -5   10   20]]


In [3]:
n = Af.shape[0] #размерность

In [4]:
#упростим себе жизнь и отдельно запишем в массивы значения A, B, C, F
A = np.array([0] + [Af[i+1, i] for i in range(n - 1)])
C = np.array([Af[i, i] for i in range(n)])
B = np.array([Af[i-1, i] for i in range(1, n)] + [0])
F = Af.T[Af.shape[1] - 1]

print("A: ", A)
print("C: ", C)
print("B: ", B)
print("F: ", F)

A:  [ 0 -3 -5 -6 -5]
C:  [ 2  8 12 18 10]
B:  [-1 -1  2 -4  0]
F:  [ -25   72  -69 -156   20]


Для упрощения, возьмем значения краевых условий
$$q_0 = 0,\; q_{n+1} = 0 \;\Rightarrow\; \alpha_1 = 0,\; \beta_1 = 0$$

In [5]:
#вычислим прогоночные коэффициенты
alpha = np.empty(n+1)
beta = np.empty(n+1)

alpha[0] = 0
beta[0] = 0

for i in range(n):
    alpha[i + 1] = -B[i] / (A[i] * alpha[i] + C[i])
    beta[i + 1] = (F[i] - A[i]*beta[i])/(A[i] * alpha[i] + C[i])
    
print("alpha:", alpha)
print("beta:", beta)

alpha: [ 0.          0.5         0.15384615 -0.17808219  0.20977011  0.        ]
beta: [  0.         -12.5          5.30769231  -3.78082192  -9.37068966  -3.        ]


Так как $q_{n+1} = 0 \Rightarrow x_{n+1} = 0$

In [6]:
#вычислим значения корней
x = np.empty(n)

#отдельно вычислим n-ый корень
x[n-1] = beta[n]

for i in range(n - 2, -1, -1):
    x[i] = alpha[i+1] * x[i+1] + beta[i+1]
    
print("x:", x)

x: [-10.   5.  -2. -10.  -3.]


С Вольфрамом совпадает.